name: "Leetcode Integration"
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  Leetcode:
    name: "Leetcode Integration"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install requests

      - name: Run leetcode python code
        run: |
            python "leetcode_data.py"

      - name: Commit data.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "current Leetcode data"
          file_pattern: "*.json"
          repository: .
          skip_fetch: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

